name: Tests

on:
  - push

jobs:
  test:
    runs-on: ${{matrix.os}}
    env: 
      QT_QPA_PLATFORM: offscreen
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install tox tox-gh-actions
      - name: Installing PyQt5
        run: |
          pip install PyQt5==5.15.9
          pip install pyqt5-plugins==5.15.9.2.3
          pip install pyqt5-tools==5.15.9.3.3

      - name: Test with tox
        run: |
          echo Python ${{matrix.python-version}}
          tox -e py${{matrix.python-version}}
      - name: Test Linting
        run: tox -e flake8
